library(quantmod)
if (!require("quantmod"))
{ install.packages("quantmod")
  library(quantmod)}
install.packages("RCurl")
library(RCurl)
start <- as.Date("2018-08-01")
end <- as.Date("2018-09-01")
getSymbols("MRK",src = "yahoo", from = start, to = end)
train <- MRK
str(train)
plot(train[,'MRK.Close'],main = "train")
View(train)
candleChart(train,up.col="black",dn.col="red" ,theme = "white")
candleChart(train,up.col="black",dn.col="red" ,theme = "white")
set.seed(06)
addSMA(n=6)
candleChart(train,up.col="black",dn.col="red" ,theme = "white")
addSMA(n=c(10,20))
library(forecast)
library(tseries)
install.packages("lmtest")
library(lmtest)
tsdata <- train$MRK.Close
tsdata <- ts(tsdata, frequency = 7)
tsdata <- tsclean(na.omit(tsdata))
tsclean <- stl(tsdata[,1] , s.window = "periodic")
plot(tsclean)
deseasonal_tsclean <- seasadj(tsclean)
adf.test(deseasonal_tsclean, alternative = "stationary")
Acf(tsdata, main='')
Pacf(tsdata, main='')
tsclean_d1 = diff(deseasonal_tsclean, differences = 1)
plot(tsclean_d1)
adf.test(deseasonal_tsclean, alternative = "stationary")
Acf(tsclean_d1, main='ACF for Differenced Series')
Pacf(tsclean_d1, main='PACF for Differenced Series')
auto.arima(deseasonal_tsclean, seasonal=FALSE)
fit<-auto.arima(deseasonal_tsclean, seasonal=FALSE)
tsdisplay(residuals(fit), lag.max=15, main='(0,1,0) Model Residuals')
fit<-auto.arima(deseasonal_tsclean, seasonal=FALSE)
plot()
tsdisplay(residuals(fit), lag.max=15, main='(2,1,4) Model Residuals')
fit2model <- forecast(fit,100)
plot(fit2model)

start <- as.Date("2018-09-01")
end <- as.Date("2018-10-16")
getSymbols("MRK",src = "yahoo", from = start, to = end)
test <- MRK
test1 <- forecast(fit,30)
library(caret)
#install.packages("Metrics")
tsdata1 <- test$MRK.Close
tsdata1 <- ts(tsdata1, frequency = 7)
tsdata1 <- tsclean(na.omit(tsdata1))
tsdata1 <- as.data.frame(tsdata1)
library(Metrics)
test1 <- as.data.frame(test1)
testcol <- as.data.frame(test1[,1])
mape(tsdata1$MRK.Close,testcol$`test1[, 1]`)
